kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "10.26.14.24"
  apiServerPort: 6443
nodes:
- role: control-plane
  # patch the generated kubeadm config with some extra settings
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        # dex will be deployed in `dex` namespace, exposed by `dex` svc
        oidc-issuer-url: https://dex-dev.matveeva.space:32000
        # the client-id that is inbuilt in the example-app
        oidc-client-id: example-app
        # the CA that we generated for Dex
        oidc-ca-file: /etc/ssl/certs/dex/ca.pem
        # email will be used as the claim
        oidc-username-claim: email
        oidc-groups-claim: groups
    kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP

  extraMounts:
  - hostPath: "${PROJECT_ROOT}/tls-setup/_certs"
    containerPath: /etc/ssl/certs/dex
- role: worker
