apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-auth-dex
  namespace: kube-system
spec:
  secretName: cert-auth-dex
  dnsNames:
    - dex-dev.matveeva.space
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - dex-dev.matveeva.space
  issuerRef:
    name: le-clusterissuer-staging
    kind: ClusterIssuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-auth-login
  namespace: kube-system
spec:
  secretName: cert-auth-login
  dnsNames:
    - login-dev.matveeva.space
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - login-dev.matveeva.space
  issuerRef:
    name: le-clusterissuer-staging
    kind: ClusterIssuer