apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-clusterissuer-staging
  namespace: kube-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: traublemak@yandex.ru
    privateKeySecretRef:
      name: le-clusterissuer
    http01: {}
